### ISSUE TITLE
Tinderable is not a class

### ISSUE THREAD

**Issue by dasoga** [orkhanalizade/Tinderable#1]
Hey dude thanks for this.
But it doesn't work. Tinder able is not a name of the class so not can be call.

And i'm calling "TinderableView" but same, doesn't work.
I appreciate if you can update this. Thanks!

**Comment by orkhanalizade** [comment]
Just use it as:

    swipeableView = TinderableView()

and later use

    swipeableView.some_method_here

**Comment by orkhanalizade** [comment]
@dasoga I've updated it and putted an Example project into the repository, so you can just clone Tinderable repository and use it. ReadMe file has been updated, also.
